### PR TITLE
feat: completion time

### PR DESCRIPTION
**Pull request by gf3**
This PR adds support for optionally including completion time as well as a handful of settings to configure the functionality of the plugin.

The new settings include:

- **Task markers** - Task markers to use (default: `"DONE, NOW, LATER, DOING, TODO, WAITING"`)
- **Include date?** - Optionally include date (default: `true`)
- **Completed date property** - Property to use for completed date (default: `"completed"`)
- **Include time?** - Optionally include time (default: `false`)
- **Completed time property** - Property to use for completed date (default: `"time"`)
- **Time format** - Time format when including time (default: `HH:mm`)

image

I've also updated the dependencies and tidied up the build a bit (no more html).

And lastly, I've added a dev container configuration which includes all the dependencies necessary to develop this plugin.

### CODE REVIEW

**Comment by DimitryDushkin** [comment]
Hey @gf3 ! Thanks a lot for such a great contribution! I removed files related to your personal dev env if you don't mind.

**Comment by gf3** [comment]
@DimitryDushkin sure thing! however, the dev container config makes it easy for others to automatically have a working environment to hack on this plugin. see: 

- https://containers.dev/
- https://code.visualstudio.com/docs/devcontainers/containers

**Comment by DimitryDushkin** [comment]
Published 2.0! https://github.com/DimitryDushkin/logseq-plugin-task-check-date/releases/tag/2.0

**Comment by DimitryDushkin** [comment]
> @DimitryDushkin sure thing! however, the dev container config makes it easy for others to automatically have a working environment to hack on this plugin. see:
> 
> * https://containers.dev/
> * https://code.visualstudio.com/docs/devcontainers/containers

Yeah, it looks cool. But sorry I'm not super familiar with devcontainers so I'm not able to review this correctly.

**Comment by DimitryDushkin** [comment]
And it's not working. I forgot that Logseq actually not working when loaded just JS file. It always needs to load html. See https://github.com/logseq/logseq/issues/10117

**Comment by DimitryDushkin** [comment]
Updated build. Now it's working out of marketplace again.

@gf3 thanks again for the contribution. If you will have a moment could you take a look at settings update issue? Settings are not applied unless you restart the app now.

**Comment by gf3** [comment]
@DimitryDushkin i will have a look, thanks for the fixes. i didn't realize there was an issue with loading JS files directly in non-developer mode. my apologies for the breakage!

**Pull request merged**
